### ISSUE TITLE
'application note' vignette

### ISSUE THREAD

**Issue by rvosa** [ropensci/nbaR#15]
Draft a vignette (±2-3 pages) that outlines the main functionality as relevant to a scientific end user: what data can I get and how do I get it?

**Comment by rvosa** [comment]
This can now be written on the basis of the vignettes from #14

**Comment by rvosa** [comment]
Who are coauthors? As of https://github.com/naturalis/nbaR/commit/94d747d2397aa805a9c936925f820043c500d9d0 the manuscript skeleton has @hettling and @rvosa on it.

**Comment by maelle** [comment]
This package will be archived as an API update broke it.
