### ISSUE TITLE
First link in README.md doesn't work

### ISSUE THREAD

**Issue by marijn-naturalis** [ropensci/nbaR#59]
Netherlands Biodiversity API (docs.biodiversitydata.nl) gives a 404 error.

**Comment by hettling** [comment]
This works now, uses the URL docs.biodiversitydata.nl/en/latest/.
This is an still an issue to be addressed by infra: In te past, docs.biodiversitydata.nl did a redirect to docs.biodiversitydata.nl/en/latest/, since the latest migration of the NBA this redirect does not exist anymore.
