### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/nbaR#64]
Or new maintainer team. :smile_cat: 

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html).

**Comment by maelle** [comment]
I'll leave this open one more month to account for the summer.

**Comment by KevCaz** [comment]
@maelle I can have a look if I would be able to maintain this package!

**Comment by KevCaz** [comment]
@maelle I should be able to do it, think II have enough experience with Java to use swagger-codegen, working a bit on the package in a fork right now.

**Comment by maelle** [comment]
Thanks a ton @KevCaz, I've added you to a team with admin access to this repository! :rocket: 

Could you please add yourself as `c("aut", "cre")` to the `DESCRIPTION` file and remove the "cre" role of the former maintainer?

Feel free to ping me with any question on GitHub or in rOpenSci Slack workspace (where you know the #package-maintenance channel :wink:)
